/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-04-04 09:32:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.appusers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class working_jspx extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div version=\"2.0\">");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f5(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f6(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f7(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f8(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f9(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fset_005f10(_jspx_page_context))
        return;
      out.write("<div class=\"form-group\">");
      out.write("<div role=\"tabpanel\">");
      out.write("<div class=\"tab-content\">");
      out.write("<div aria-multiselectable=\"true\" role=\"tablist\" id=\"tab1\" class=\"panel-group\">");
      out.write("<div class=\"panel panel-default\">");
      out.write("<div role=\"tab\" class=\"panel-heading\">");
      out.write("<h4 class=\"panel-title\">");
      out.write("<a aria-controls=\"training_internal_history\" aria-expanded=\"false\" href=\"#leave_history\" data-parent=\"#tab1\" data-toggle=\"collapse\" caret=\"0\" class=\"collapsed\" id=\"collapse1\">");
      out.write("\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leave_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                                ");
      out.write("</a>");
      out.write("<span class=\"fa fa-caret-up\" value=\"0\" id=\"caretdown1\">");
      out.write("</span>");
      out.write("</h4>");
      out.write("</div>");
      out.write("<div aria-labelledby=\"leave_history\" role=\"tabpanel\" class=\"panel-collapse collapse in\" id=\"leave_history\">");
      out.write("<div class=\"table-responsive\">");
      out.write("<table role=\"table\" class=\"table table-hover\">");
      out.write("<thead>");
      out.write("<tr>");
      out.write("<th rowspan=\"2\">");
      out.write("วันที่เริ่มขอลา");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("วันที่สิ้นสุดขอลา");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("ประเภทการลา");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("ลาทั้งหมด");
      out.write("</center>");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("หมายเหตุ");
      out.write("</th>");
      out.write("</tr>");
      out.write("<tr>");
      out.write("<th colspan=\"1\">");
      out.write('ว');
      out.write('ั');
      out.write('น');
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("ชั่วโมง/นาที");
      out.write("</th>");
      out.write("</tr>");
      out.write("</thead>");
      out.write("<tbody id=\"tbody_leave_history\"/>");
      out.write("</table>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("<div class=\"form-group\">");
      out.write("<div role=\"tabpanel\">");
      out.write("<div class=\"tab-content\">");
      out.write("<div aria-multiselectable=\"true\" role=\"tablist\" id=\"tab1\" class=\"panel-group\">");
      out.write("<div class=\"panel panel-default\">");
      out.write("<div role=\"tab\" class=\"panel-heading\">");
      out.write("<h4 class=\"panel-title\">");
      out.write("<a aria-controls=\"training_external_history\" aria-expanded=\"false\" href=\"#leave_balance\" data-parent=\"#tab1\" data-toggle=\"collapse\" caret=\"0\" class=\"collapsed\" id=\"collapse2\">");
      out.write("\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leave_balance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                                ");
      out.write("</a>");
      out.write("<span class=\"fa fa-caret-up\" value=\"0\" id=\"caretdown2\">");
      out.write("</span>");
      out.write("</h4>");
      out.write("</div>");
      out.write("<div aria-labelledby=\"leave_balance\" role=\"tabpanel\" class=\"panel-collapse collapse in\" id=\"leave_balance\">");
      out.write("<div class=\"table-responsive\">");
      out.write("<table role=\"table\" class=\"table table-hover\">");
      out.write("<thead>");
      out.write("<tr>");
      out.write("<th rowspan=\"2\">");
      out.write("รหัสประเภทการลา");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("ชื่อประเภทการลา");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("จำนวนวันลาต่อปี");
      out.write("</center>");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("จำนวนวันลา");
      out.write("</center>");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("ยอดสะสมคงเหลือ");
      out.write("</center>");
      out.write("</th>");
      out.write("</tr>");
      out.write("<tr>");
      out.write("<th colspan=\"1\">");
      out.write("จำนวนวัน");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("ชั่วโมง/นาที");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("จำนวนวัน");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("ชั่วโมง/นาที");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("จำนวนวัน");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("ชั่วโมง/นาที");
      out.write("</th>");
      out.write("</tr>");
      out.write("</thead>");
      out.write("<tbody id=\"tbody_leave_balance\"/>");
      out.write("</table>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("<div class=\"form-group\">");
      out.write("<div role=\"tabpanel\">");
      out.write("<div class=\"tab-content\">");
      out.write("<div aria-multiselectable=\"true\" role=\"tablist\" id=\"tab1\" class=\"panel-group\">");
      out.write("<div class=\"panel panel-default\">");
      out.write("<div role=\"tab\" class=\"panel-heading\">");
      out.write("<h4 class=\"panel-title\">");
      out.write("<a aria-controls=\"trainner_history\" aria-expanded=\"false\" href=\"#detail_inout\" data-parent=\"#tab1\" data-toggle=\"collapse\" caret=\"0\" class=\"collapsed\" id=\"collapse3\">");
      out.write("\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inout_time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                                ");
      out.write("</a>");
      out.write("<span class=\"fa fa-caret-up\" value=\"0\" id=\"caretdown3\">");
      out.write("</span>");
      out.write("</h4>");
      out.write("</div>");
      out.write("<div aria-labelledby=\"detail_inout\" role=\"tabpanel\" class=\"panel-collapse collapse in\" id=\"detail_inout\">");
      out.write("<div class=\"table-responsive\">");
      out.write("<table role=\"table\" class=\"table table-hover\">");
      out.write("<thead>");
      out.write("<tr>");
      out.write("<th rowspan=\"2\">");
      out.write("วันที่");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("เวลาเข้างาน");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("เวลาออกงาน");
      out.write("</th>");
      out.write("<th rowspan=\"2\">");
      out.write("สถานะการทำงาน");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("เวลาทำงาน");
      out.write("</center>");
      out.write("</th>");
      out.write("</tr>");
      out.write("<tr>");
      out.write("<th colspan=\"1\">");
      out.write("ชั่วโมง");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("นาที");
      out.write("</th>");
      out.write("</tr>");
      out.write("</thead>");
      out.write("<tbody id=\"tbody_detail_inout\"/>");
      out.write("</table>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("<div class=\"form-group\">");
      out.write("<div role=\"tabpanel\">");
      out.write("<div class=\"tab-content\">");
      out.write("<div aria-multiselectable=\"true\" role=\"tablist\" id=\"tab1\" class=\"panel-group\">");
      out.write("<div class=\"panel panel-default\">");
      out.write("<div role=\"tab\" class=\"panel-heading\">");
      out.write("<h4 class=\"panel-title\">");
      out.write("<a aria-controls=\"trainner_history\" aria-expanded=\"false\" href=\"#OT_history\" data-parent=\"#tab1\" data-toggle=\"collapse\" caret=\"0\" class=\"collapsed\" id=\"collapse4\">");
      out.write("\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${OT_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                                ");
      out.write("</a>");
      out.write("<span class=\"fa fa-caret-up\" value=\"0\" id=\"caretdown4\">");
      out.write("</span>");
      out.write("</h4>");
      out.write("</div>");
      out.write("<div aria-labelledby=\"OT_history\" role=\"tabpanel\" class=\"panel-collapse collapse in\" id=\"OT_history\">");
      out.write("<div class=\"table-responsive\">");
      out.write("<table role=\"table\" class=\"table table-hover\">");
      out.write("<thead>");
      out.write("<tr>");
      out.write("<th rowspan=\"2\">");
      out.write("วันที่ทำ OT");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("ก่อนเวลาเข้างาน");
      out.write("</center>");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("เวลาเข้างานก่อนพัก");
      out.write("</center>");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("เวลาเข้างานหลังพัก");
      out.write("</center>");
      out.write("</th>");
      out.write("<th colspan=\"2\" rowspan=\"1\">");
      out.write("<center>");
      out.write("เวลาหลังเลิกงาน");
      out.write("</center>");
      out.write("</th>");
      out.write("</tr>");
      out.write("<tr>");
      out.write("<th colspan=\"1\">");
      out.write("เริ่มต้น");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("สิ้นสุด");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("เริ่มต้น");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("สิ้นสุด");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("เริ่มต้น");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("สิ้นสุด");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("เริ่มต้น");
      out.write("</th>");
      out.write("<th colspan=\"1\">");
      out.write("สิ้นสุด");
      out.write("</th>");
      out.write("</tr>");
      out.write("</thead>");
      out.write("<tbody id=\"tbody_OT_history\"/>");
      out.write("</table>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("</div>");
      out.write("<script type=\"text/javascript\">");
      out.write("\n");
      out.write("\n");
      out.write("        var startDate = '', endDate = '', annual = '', dateBegin = '', dateEnd = '', dataJsonIn, dataJsonEx, dataJsonTrainer;\n");
      out.write("        var messageWorking = {};\n");
      out.write("\n");
      out.write("        messageWorking.noLeaveReqHis = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no_leave_request_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.noLeaveBalHis = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no_leave_balance_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.noTADailyHistory = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no_ta_daily_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.noOtHistory = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${no_ot_history}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.notPass = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not_pass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.pass = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pass}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("        messageWorking.ultimateLeave = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ultimate_leave}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\n");
      out.write("        $(\"#_startDate_text_id\").val(session['startoffical']);\n");
      out.write("        $(\"#_endDate_text_id\").val(session['endoffical']);\n");
      out.write("        $(\"#_startDate_text_id\").val(showDateByLang($(\"#_startDate_text_id\").val()));\n");
      out.write("        $(\"#_endDate_text_id\").val(showDateByLang($(\"#_endDate_text_id\").val()));\n");
      out.write("\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            $(\"#collapse1\").click(function () {\n");
      out.write("                var value = $(\"#caretdown1\").attr('value');\n");
      out.write("                if (value === '0') {\n");
      out.write("                    $(\"#caretdown1\").attr('value', '1');\n");
      out.write("                    $(\"#caretdown1\").attr('class', 'fa fa-caret-down');\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    $(\"#caretdown1\").attr('value', '0');\n");
      out.write("                    $(\"#caretdown1\").attr('class', 'fa fa-caret-up');\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\"#collapse2\").click(function () {\n");
      out.write("                var value = $(\"#caretdown2\").attr('value');\n");
      out.write("                if (value === '0') {\n");
      out.write("                    $(\"#caretdown2\").attr('value', '1');\n");
      out.write("                    $(\"#caretdown2\").attr('class', 'fa fa-caret-down');\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    $(\"#caretdown2\").attr('value', '0');\n");
      out.write("                    $(\"#caretdown2\").attr('class', 'fa fa-caret-up');\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\"#collapse3\").click(function () {\n");
      out.write("                var value = $(\"#caretdown3\").attr('value');\n");
      out.write("                if (value === '0') {\n");
      out.write("                    $(\"#caretdown3\").attr('value', '1');\n");
      out.write("                    $(\"#caretdown3\").attr('class', 'fa fa-caret-down');\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    $(\"#caretdown3\").attr('value', '0');\n");
      out.write("                    $(\"#caretdown3\").attr('class', 'fa fa-caret-up');\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\"#collapse4\").click(function () {\n");
      out.write("                var value = $(\"#caretdown4\").attr('value');\n");
      out.write("                if (value === '0') {\n");
      out.write("                    $(\"#caretdown4\").attr('value', '1');\n");
      out.write("                    $(\"#caretdown4\").attr('class', 'fa fa-caret-down');\n");
      out.write("                }\n");
      out.write("                else {\n");
      out.write("                    $(\"#caretdown4\").attr('value', '0');\n");
      out.write("                    $(\"#caretdown4\").attr('class', 'fa fa-caret-up');\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            setDate();\n");
      out.write("            getLeaveRequest();\n");
      out.write("            getLeaveBalance();\n");
      out.write("            getTADaily();\n");
      out.write("            getOTRequest()\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function setDate() {\n");
      out.write("            dateBegin = sendDateToBase($('input[id=_startDate_text_id]').val());\n");
      out.write("            dateEnd = sendDateToBase($('input[id=_endDate_text_id]').val());\n");
      out.write("//        annual = startDate.split('/')[2];\n");
      out.write("            annual = 2015;\n");
      out.write("            var spStartDate = dateBegin.split(\"/\");\n");
      out.write("            var spEndDate = dateEnd.split(\"/\");\n");
      out.write("            startDate = new Date().setFullYear(spStartDate[2], spStartDate[1] - 1, spStartDate[0]);\n");
      out.write("            endDate = new Date().setFullYear(spEndDate[2], spEndDate[1] - 1, spEndDate[0]);\n");
      out.write("//            console.log(new Date(startDate));\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        //Internal training\n");
      out.write("        function getLeaveRequest() {\n");
      out.write("//        setDate();\n");
      out.write("            $(\"#tbody_leave_history\").empty();\n");
      out.write("            dataJsonIn = getLeaveRequestByEmpCodeAndDate('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', sendDateToBase($('input[id=_startDate_text_id]').val()), sendDateToBase($('input[id=_endDate_text_id]').val()));\n");
      out.write("            if (dataJsonIn != '' && dataJsonIn.length > 0) {\n");
      out.write("                var count = 1;\n");
      out.write("                $.each(dataJsonIn, function (key, value) {\n");
      out.write("                    var leaveType = value.leaveType.leaveTypeName;\n");
      out.write("                    var cbStartDate = new Date(value.startDateLeave);\n");
      out.write("                    var cbEndDate = new Date(value.endDateLeave);\n");
      out.write("\n");
      out.write("//                    if (new Date(startDate) <= cbEndDate && new Date(endDate) >= cbStartDate) {\n");
      out.write("                        var dateSShow = cbStartDate.getDate() + \"/\" + (cbStartDate.getMonth() + 1) + \"/\" + cbStartDate.getFullYear();\n");
      out.write("                        var dateEShow = cbEndDate.getDate() + \"/\" + (cbEndDate.getMonth() + 1) + \"/\" + cbEndDate.getFullYear();\n");
      out.write("                        var reference = value.reference == null || value.reference == \"\" ? \"-\" : value.reference;\n");
      out.write("                        $(\"#tbody_leave_history\").append(\n");
      out.write("                                '<tr>' +\n");
      out.write("                                '<td class=\"text-center\">' + showDateByLang(dateSShow) + '</td>' +\n");
      out.write("                                '<td class=\"text-center\">' + showDateByLang(dateEShow) + '</td>' +\n");
      out.write("                                '<td>' + leaveType + '</td>' +\n");
      out.write("                                '<td class=\"text-center\">' + value.dateLeave + '</td>' +\n");
      out.write("                                '<td class=\"text-center\">' + value.hourLeave + '.' + value.miniuteLeave + '</td>' +\n");
      out.write("                                '<td class=\"text-center\">' + reference + '</td>' +\n");
      out.write("                                '</tr>'\n");
      out.write("                        );\n");
      out.write("                        count++;\n");
      out.write("//                    }\n");
      out.write("                });\n");
      out.write("//                if (count == 1) {\n");
      out.write("//                    $(\"#tbody_leave_history\").append(\n");
      out.write("//                            '<tr>' +\n");
      out.write("//                            '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noLeaveReqHis + '</td>' +\n");
      out.write("//                            '</tr>'\n");
      out.write("//                    );\n");
      out.write("//                }\n");
      out.write("            } else {\n");
      out.write("                $(\"#tbody_leave_history\").append(\n");
      out.write("                        '<tr>' +\n");
      out.write("                        '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noLeaveReqHis + '</td>' +\n");
      out.write("                        '</tr>'\n");
      out.write("                );\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        }\n");
      out.write("        //External training\n");
      out.write("        function getLeaveBalance() {\n");
      out.write("            setDate();\n");
      out.write("            $(\"#tbody_leave_balance\").empty();\n");
      out.write("            dataJsonEx = getRemainingTimeOfLeaveByEmpCodeAndDate('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', sendDateToBase($('input[id=_startDate_text_id]').val()).split(\"/\")[2]);\n");
      out.write("            if (dataJsonEx != '' && dataJsonEx.length > 0) {\n");
      out.write("                var count = 1;\n");
      out.write("                $.each(dataJsonEx, function (key, value) {\n");
      out.write("//                var dataCourseBatch = getCourseBatchById(value.resultGenerator);\n");
      out.write("//                var cbStartDate = new Date(value.startDateLeave);\n");
      out.write("\n");
      out.write("\n");
      out.write("//                    var dateForShow = cbStartDate.getDate() + \"/\" + (cbStartDate.getMonth() + 1) + \"/\" + cbStartDate.getFullYear() + \" - \" +\n");
      out.write("//                            cbEndDate.getDate() + \"/\" + (cbEndDate.getMonth() + 1) + \"/\" + cbEndDate.getFullYear();\n");
      out.write("//                    var result = value.traineeResult == 0 ? messageWorking.notPass : (value.traineeResult == 1 ? messageWorking.pass : \"\");\n");
      out.write("                    if (value.strLeave == \"1\") {\n");
      out.write("                        var ultimateLeave = value.ultimate != \"\" && value.ultimate != null ? messageWorking.ultimateLeave : \"\";\n");
      out.write("                        $(\"#tbody_leave_balance\").append(\n");
      out.write("                                '<tr>' +\n");
      out.write("                                '<td>' + value.leaveType.leaveTypeCode + '</td>' +\n");
      out.write("                                '<td>' + value.leaveType.leaveTypeName + '</td>' +\n");
      out.write("                                '<td>' + ultimateLeave + '</td>' +\n");
      out.write("                                '<td>' + ultimateLeave + '</td>' +\n");
      out.write("                                '<td>' + value.sumLeave + '</td>' +\n");
      out.write("                                '<td >' + value.hourLeave + '.' + value.minutesLeave + '</td>' +\n");
      out.write("                                '<td >' + ultimateLeave + '</td>' +\n");
      out.write("                                '<td >' + /*value.hourLeaveBalance+'.'+value.minuteLeaveBalance*/ultimateLeave + '</td>' +\n");
      out.write("                                '</tr>'\n");
      out.write("                        );\n");
      out.write("                    } else {\n");
      out.write("                        if (value.leaveTotalBalanceHour == null) {\n");
      out.write("                            value.leaveTotalBalanceHour = 0;\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("                        $(\"#tbody_leave_balance\").append(\n");
      out.write("                                '<tr>' +\n");
      out.write("                                '<td>' + value.leaveType.leaveTypeCode + '</td>' +\n");
      out.write("                                '<td>' + value.leaveType.leaveTypeName + '</td>' +\n");
      out.write("                                '<td>' + value.leaveTotalBalance + '</td>' +\n");
      out.write("                                '<td>' +value.leaveTotalBalanceHour +'</td>' +\n");
      out.write("                                '<td>' + value.sumLeave + '</td>' +\n");
      out.write("                                '<td >' + value.hourLeave + '.' + value.minutesLeave + '</td>' +\n");
      out.write("                                '<td >' + value.leaveBalance + '</td>' +\n");
      out.write("                                '<td >' + value.hourLeaveBalance + '.' + value.minuteLeaveBalance + '</td>' +\n");
      out.write("                                '</tr>'\n");
      out.write("                        );\n");
      out.write("                    }\n");
      out.write("                    count++;\n");
      out.write("//                }\n");
      out.write("                });\n");
      out.write("                if (count == 1) {\n");
      out.write("                    $(\"#tbody_leave_balance\").append(\n");
      out.write("                            '<tr>' +\n");
      out.write("                            '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noLeaveBalHis + '</td>' +\n");
      out.write("                            '</tr>'\n");
      out.write("                    );\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                $(\"#tbody_leave_balance\").append(\n");
      out.write("                        '<tr>' +\n");
      out.write("                        '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noLeaveBalHis + '</td>' +\n");
      out.write("                        '</tr>'\n");
      out.write("                );\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        //trainer\n");
      out.write("        function getTADaily() {\n");
      out.write("            $(\"#tbody_detail_inout\").empty();\n");
      out.write("            dataJsonTrainer = getTADailyByEmpCodeAndDate('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', sendDateToBase($('input[id=_startDate_text_id]').val()), sendDateToBase($('input[id=_endDate_text_id]').val()));\n");
      out.write("            if (dataJsonTrainer != '' && dataJsonTrainer.length > 0) {\n");
      out.write("                var count = 1;\n");
      out.write("                $.each(dataJsonTrainer, function (key, value) {\n");
      out.write("                    var timeIn = \"-\";\n");
      out.write("\n");
      out.write("                            if(value.timeAttendanceHistory.otInBeforeWorking == \"null\" ||\n");
      out.write("                                    value.timeAttendanceHistory.otInBeforeWorking == null ||\n");
      out.write("                                    value.timeAttendanceHistory.otInBeforeWorking == \"\" ){\n");
      out.write("                               if(value.timeAttendanceHistory.timeInBeforeBreak != null){\n");
      out.write("                                   timeIn = value.timeAttendanceHistory.timeInBeforeBreak;\n");
      out.write("                               }else{\n");
      out.write("                                   if(value.timeAttendanceHistory.otInAfterWorking != null){\n");
      out.write("                                       timeIn = value.timeAttendanceHistory.otInAfterWorking;\n");
      out.write("                                   }\n");
      out.write("                               }\n");
      out.write("                            }else{\n");
      out.write("                                timeIn = value.timeAttendanceHistory.otInBeforeWorking;\n");
      out.write("                            };\n");
      out.write("                    var timeOut = \"-\";\n");
      out.write("\n");
      out.write("                            if(value.timeAttendanceHistory.otOutAfterWorking == \"null\" ||\n");
      out.write("                                    value.timeAttendanceHistory.otOutAfterWorking == null ||\n");
      out.write("                                    value.timeAttendanceHistory.otOutAfterWorking == \"\" ) {\n");
      out.write("                                        if(value.timeAttendanceHistory.timeOutAfterBreak != null){\n");
      out.write("                                            timeOut = value.timeAttendanceHistory.timeOutAfterBreak;\n");
      out.write("                                        }else{\n");
      out.write("                                            if(value.timeAttendanceHistory.otOutAfterWorking != null){\n");
      out.write("                                                timeOut = value.timeAttendanceHistory.otOutAfterWorking;\n");
      out.write("                                            }\n");
      out.write("                                        }\n");
      out.write("                            }else{\n");
      out.write("                                timeOut = value.timeAttendanceHistory.otOutAfterWorking;\n");
      out.write("                                }\n");
      out.write("\n");
      out.write("                    var cbStartDate = new Date(value.dateWorking);\n");
      out.write("//                var cbEndDate = new Date(value.endDateLeave);\n");
      out.write("//                if (new Date(startDate) <= cbEndDate && new Date(endDate) >= cbStartDate) {\n");
      out.write("                    var dateForShow = cbStartDate.getDate() + \"/\" + (cbStartDate.getMonth() + 1) + \"/\" + cbStartDate.getFullYear();\n");
      out.write("                    /*+ \" - \" +\n");
      out.write("                     cbEndDate.getDate() + \"/\" + (cbEndDate.getMonth() + 1) + \"/\" + cbEndDate.getFullYear();*/\n");
      out.write("                    $(\"#tbody_detail_inout\").append(\n");
      out.write("                            '<tr>' +\n");
      out.write("                            '<td class=\"text-center\">' + showDateByLang(dateForShow) + '</td>' +\n");
      out.write("                            '<td>' + timeIn + '</td>' +\n");
      out.write("                            '<td>' + timeOut + '</td>' +\n");
      out.write("                            '<td>' + value.workingStatus.workingStatusName + '</td>' +\n");
      out.write("                            '<td>' + value.hours + '</td>' +\n");
      out.write("                            '<td>' + value.minutes + '</td>' +\n");
      out.write("                            '</tr>'\n");
      out.write("                    );\n");
      out.write("                    count++;\n");
      out.write("                });\n");
      out.write("                if (count == 1) {\n");
      out.write("                    $(\"#tbody_detail_inout\").append(\n");
      out.write("                            '<tr>' +\n");
      out.write("                            '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noTADailyHistory + '</td>' +\n");
      out.write("                            '</tr>'\n");
      out.write("                    );\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                $(\"#tbody_detail_inout\").append(\n");
      out.write("                        '<tr>' +\n");
      out.write("                        '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noTADailyHistory + '</td>' +\n");
      out.write("                        '</tr>'\n");
      out.write("                );\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function getOTRequest() {\n");
      out.write("            $(\"#tbody_OT_history\").empty();\n");
      out.write("            dataJsonTrainer = getOTRequestByEmpCodeAndDate('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', sendDateToBase($('input[id=_startDate_text_id]').val()), sendDateToBase($('input[id=_endDate_text_id]').val()));\n");
      out.write("            if (dataJsonTrainer != '' && dataJsonTrainer.length > 0) {\n");
      out.write("                var count = 1;\n");
      out.write("                $.each(dataJsonTrainer, function (key, value) {\n");
      out.write("//                var dataCourseBatch = getCourseBatchById(value.batchId);\n");
      out.write("                    var cbStartDate = new Date(value.otDate);\n");
      out.write("                    var beforeWorkingOTStart = value.beforeWorkingOTStart == null || value.beforeWorkingOTStart == \"\" ? \"-\" : value.beforeWorkingOTStart;\n");
      out.write("                    var beforeWorkingOTEnd = value.beforeWorkingOTEnd == null || value.beforeWorkingOTEnd == \"\" ? \"-\" : value.beforeWorkingOTEnd;\n");
      out.write("                    var beforeBreakeOTStart = value.beforeBreakeOTStart == null || value.beforeBreakeOTStart == \"\" ? \"-\" : value.beforeBreakeOTStart;\n");
      out.write("                    var beforeBreakeOTEnd = value.beforeBreakeOTEnd == null || value.beforeBreakeOTEnd == \"\" ? \"-\" : value.beforeBreakeOTEnd;\n");
      out.write("                    var afterBreakeOTStart = value.afterBreakeOTStart == null || value.afterBreakeOTStart == \"\" ? \"-\" : value.afterBreakeOTStart;\n");
      out.write("                    var afterBreakeOTEnd = value.afterBreakeOTEnd == null || value.afterBreakeOTEnd == \"\" ? \"-\" : value.afterBreakeOTEnd;\n");
      out.write("                    var afterWorkingOTStart = value.afterWorkingOTStart == null || value.afterWorkingOTStart == \"\" ? \"-\" : value.afterWorkingOTStart;\n");
      out.write("                    var afterWorkingOTEnd = value.afterWorkingOTEnd == null || value.afterWorkingOTEnd == \"\" ? \"-\" : value.afterWorkingOTEnd;\n");
      out.write("//                var hourOT = value.hourOT==null||value.hourOT==\"\"?\"-\":value.hourOT;\n");
      out.write("//                var minutesOT = value.minutesOT==null||value.minutesOT==\"\"?\"-\":value.minutesOT;\n");
      out.write("//                var cbEndDate = new Date(value.endDateLeave);\n");
      out.write("//                if (new Date(startDate) <= cbEndDate && new Date(endDate) >= cbStartDate) {\n");
      out.write("                    var dateForShow = cbStartDate.getDate() + \"/\" + (cbStartDate.getMonth() + 1) + \"/\" + cbStartDate.getFullYear();\n");
      out.write("//                           + \" - \" + cbEndDate.getDate() + \"/\" + (cbEndDate.getMonth() + 1) + \"/\" + cbEndDate.getFullYear();\n");
      out.write("                    $(\"#tbody_OT_history\").append(\n");
      out.write("                            '<tr>' +\n");
      out.write("                            '<td class=\"text-center\">' + showDateByLang(dateForShow) + '</td>' +\n");
      out.write("                            '<td>' + beforeWorkingOTStart + '</td>' +\n");
      out.write("                            '<td>' + beforeWorkingOTEnd + '</td>' +\n");
      out.write("                            '<td>' + beforeBreakeOTStart + '</td>' +\n");
      out.write("                            '<td>' + beforeBreakeOTEnd + '</td>' +\n");
      out.write("                            '<td>' + afterBreakeOTStart + '</td>' +\n");
      out.write("                            '<td>' + afterBreakeOTEnd + '</td>' +\n");
      out.write("                            '<td>' + afterWorkingOTStart + '</td>' +\n");
      out.write("                            '<td>' + afterWorkingOTEnd + '</td>' +\n");
      out.write("\n");
      out.write("                            '</tr>'\n");
      out.write("                    );\n");
      out.write("                    count++;\n");
      out.write("//                }\n");
      out.write("                });\n");
      out.write("                if (count == 1) {\n");
      out.write("                    $(\"#tbody_OT_history\").append(\n");
      out.write("                            '<tr>' +\n");
      out.write("                            '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noOtHistory + '</td>' +\n");
      out.write("                            '</tr>'\n");
      out.write("                    );\n");
      out.write("                }\n");
      out.write("            } else {\n");
      out.write("                $(\"#tbody_OT_history\").append(\n");
      out.write("                        '<tr>' +\n");
      out.write("                        '<td colspan=\"5\" class=\"text-center\">' + messageWorking.noOtHistory + '</td>' +\n");
      out.write("                        '</tr>'\n");
      out.write("                );\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        ");
      out.write("</script>");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(8,48) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(8,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("leave_history");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f0(_jspx_th_c_005fset_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f0);
      // /WEB-INF/views/appusers/working.jspx(8,111) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("label_com_spt_ess_domain_leave_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(9,48) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(9,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("leave_balance");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f1);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_c_005fset_005f1, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f1);
      // /WEB-INF/views/appusers/working.jspx(9,111) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("label_com_spt_ess_domain_leave_balance");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(10,45) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(10,45) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("inout_time");
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_eval_c_005fset_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f2);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f2(_jspx_th_c_005fset_005f2, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f2_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f2);
      // /WEB-INF/views/appusers/working.jspx(10,112) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f2.setCode("label_com_spt_ess_domain_detail_inout_time");
      int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
        if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
      _jspx_th_spring_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(11,45) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(11,45) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("OT_history");
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f3);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f3(_jspx_th_c_005fset_005f3, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f3_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f3);
      // /WEB-INF/views/appusers/working.jspx(11,105) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f3.setCode("label_com_spt_ess_domain_OT_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
        if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
      _jspx_th_spring_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(12,59) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(12,59) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("no_leave_request_history");
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_eval_c_005fset_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f4);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f4(_jspx_th_c_005fset_005f4, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f4_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f4);
      // /WEB-INF/views/appusers/working.jspx(13,79) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f4.setCode("label_com_spt_ess_domain_appuser_no_leave_request_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
        if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
      _jspx_th_spring_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f5_reused = false;
    try {
      _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f5.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(14,59) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(14,59) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f5.setVar("no_leave_balance_history");
      int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
      if (_jspx_eval_c_005fset_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f5);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f5(_jspx_th_c_005fset_005f5, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f5);
      _jspx_th_c_005fset_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f5_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f5);
      // /WEB-INF/views/appusers/working.jspx(15,79) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f5.setCode("label_com_spt_ess_domain_appuser_no_leave_balance_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f5 = _jspx_th_spring_005fmessage_005f5.doStartTag();
        if (_jspx_th_spring_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f5);
      _jspx_th_spring_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f6 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f6_reused = false;
    try {
      _jspx_th_c_005fset_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f6.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(16,48) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(16,48) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f6.setVar("no_ot_history");
      int _jspx_eval_c_005fset_005f6 = _jspx_th_c_005fset_005f6.doStartTag();
      if (_jspx_eval_c_005fset_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f6);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f6(_jspx_th_c_005fset_005f6, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f6);
      _jspx_th_c_005fset_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f6 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f6_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f6);
      // /WEB-INF/views/appusers/working.jspx(17,74) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f6.setCode("label_com_spt_ess_domain_appuser_no_ot_doing_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f6 = _jspx_th_spring_005fmessage_005f6.doStartTag();
        if (_jspx_th_spring_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f6);
      _jspx_th_spring_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f7 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f7_reused = false;
    try {
      _jspx_th_c_005fset_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f7.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(18,54) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(18,54) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f7.setVar("no_ta_daily_history");
      int _jspx_eval_c_005fset_005f7 = _jspx_th_c_005fset_005f7.doStartTag();
      if (_jspx_eval_c_005fset_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f7);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f7(_jspx_th_c_005fset_005f7, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f7);
      _jspx_th_c_005fset_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f7 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f7_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f7);
      // /WEB-INF/views/appusers/working.jspx(19,78) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f7.setCode("label_com_spt_ess_domain_appuser_no_inout_detail_history");
      int[] _jspx_push_body_count_spring_005fmessage_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f7 = _jspx_th_spring_005fmessage_005f7.doStartTag();
        if (_jspx_th_spring_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f7);
      _jspx_th_spring_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f8 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f8_reused = false;
    try {
      _jspx_th_c_005fset_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f8.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(20,43) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(20,43) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f8.setVar("not_pass");
      int _jspx_eval_c_005fset_005f8 = _jspx_th_c_005fset_005f8.doStartTag();
      if (_jspx_eval_c_005fset_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f8);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f8(_jspx_th_c_005fset_005f8, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f8);
      _jspx_th_c_005fset_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f8 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f8_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f8);
      // /WEB-INF/views/appusers/working.jspx(20,113) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f8.setCode("global_other_not_pass");
      // /WEB-INF/views/appusers/working.jspx(20,113) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f8.setJavaScriptEscape("true");
      int[] _jspx_push_body_count_spring_005fmessage_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f8 = _jspx_th_spring_005fmessage_005f8.doStartTag();
        if (_jspx_th_spring_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f8);
      _jspx_th_spring_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f9 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f9_reused = false;
    try {
      _jspx_th_c_005fset_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f9.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(21,39) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(21,39) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f9.setVar("pass");
      int _jspx_eval_c_005fset_005f9 = _jspx_th_c_005fset_005f9.doStartTag();
      if (_jspx_eval_c_005fset_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f9 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f9);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f9(_jspx_th_c_005fset_005f9, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f9 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f9);
      _jspx_th_c_005fset_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f9 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f9_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f9);
      // /WEB-INF/views/appusers/working.jspx(21,105) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f9.setCode("global_other_pass");
      // /WEB-INF/views/appusers/working.jspx(21,105) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f9.setJavaScriptEscape("true");
      int[] _jspx_push_body_count_spring_005fmessage_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f9 = _jspx_th_spring_005fmessage_005f9.doStartTag();
        if (_jspx_th_spring_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f9);
      _jspx_th_spring_005fmessage_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f9, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f10 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f10_reused = false;
    try {
      _jspx_th_c_005fset_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f10.setParent(null);
      // /WEB-INF/views/appusers/working.jspx(22,49) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setScope("request");
      // /WEB-INF/views/appusers/working.jspx(22,49) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f10.setVar("ultimate_leave");
      int _jspx_eval_c_005fset_005f10 = _jspx_th_c_005fset_005f10.doStartTag();
      if (_jspx_eval_c_005fset_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005fset_005f10 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f10);
        }
        do {
          if (_jspx_meth_spring_005fmessage_005f10(_jspx_th_c_005fset_005f10, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fset_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005fset_005f10 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005fset_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fscope.reuse(_jspx_th_c_005fset_005f10);
      _jspx_th_c_005fset_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f10, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f10 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f10_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f10.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f10);
      // /WEB-INF/views/appusers/working.jspx(23,125) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f10.setCode("label_com_spt_ess_domain_leaverequest_ultimateleave");
      // /WEB-INF/views/appusers/working.jspx(23,125) name = javaScriptEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f10.setJavaScriptEscape("true");
      int[] _jspx_push_body_count_spring_005fmessage_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f10 = _jspx_th_spring_005fmessage_005f10.doStartTag();
        if (_jspx_th_spring_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f10.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fjavaScriptEscape_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f10);
      _jspx_th_spring_005fmessage_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f10, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f10_reused);
    }
    return false;
  }
}
