/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-03-26 10:22:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jspx extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tags/menu/category.tagx", Long.valueOf(1466483538000L));
    _jspx_dependants.put("/WEB-INF/tags/menu/item.tagx", Long.valueOf(1466483538000L));
    _jspx_dependants.put("/WEB-INF/tags/menu/menu.tagx", Long.valueOf(1466483538000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div version=\"2.0\" id=\"menu\">");
      if (_jspx_meth_menu_005fmenu_005f0(_jspx_page_context))
        return;
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_menu_005fmenu_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  menu:menu
    org.apache.jsp.tag.web.menu.menu_tagx _jspx_th_menu_005fmenu_005f0 = new org.apache.jsp.tag.web.menu.menu_tagx();
    _jsp_getInstanceManager().newInstance(_jspx_th_menu_005fmenu_005f0);
    try {
      _jspx_th_menu_005fmenu_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/menu.jspx(6,60) name = z type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fmenu_005f0.setZ("nZaf43BjUg1iM0v70HJVEsXDopc=");
      // /WEB-INF/views/menu.jspx(6,60) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fmenu_005f0.setId("_menu");
      _jspx_th_menu_005fmenu_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_menu_005fmenu_005f0, null));
      _jspx_th_menu_005fmenu_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_menu_005fmenu_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_menu_005fcategory_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  menu:category
    org.apache.jsp.tag.web.menu.category_tagx _jspx_th_menu_005fcategory_005f0 = new org.apache.jsp.tag.web.menu.category_tagx();
    _jsp_getInstanceManager().newInstance(_jspx_th_menu_005fcategory_005f0);
    try {
      _jspx_th_menu_005fcategory_005f0.setJspContext(_jspx_page_context);
      _jspx_th_menu_005fcategory_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/menu.jspx(8,55) name = z type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fcategory_005f0.setZ("user-managed");
      // /WEB-INF/views/menu.jspx(8,55) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fcategory_005f0.setId("c_LB2430");
      _jspx_th_menu_005fcategory_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_menu_005fcategory_005f0, null));
      _jspx_th_menu_005fcategory_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_menu_005fcategory_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_menu_005fitem_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  menu:item
    org.apache.jsp.tag.web.menu.item_tagx _jspx_th_menu_005fitem_005f0 = new org.apache.jsp.tag.web.menu.item_tagx();
    _jsp_getInstanceManager().newInstance(_jspx_th_menu_005fitem_005f0);
    try {
      _jspx_th_menu_005fitem_005f0.setJspContext(_jspx_page_context);
      _jspx_th_menu_005fitem_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/menu.jspx(9,97) name = z type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f0.setZ("user-managed");
      // /WEB-INF/views/menu.jspx(9,97) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f0.setUrl("/emailtemplates/listEmailTemplates");
      // /WEB-INF/views/menu.jspx(9,97) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f0.setId("i_LB2436");
      _jspx_th_menu_005fitem_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_menu_005fitem_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_menu_005fcategory_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  menu:category
    org.apache.jsp.tag.web.menu.category_tagx _jspx_th_menu_005fcategory_005f1 = new org.apache.jsp.tag.web.menu.category_tagx();
    _jsp_getInstanceManager().newInstance(_jspx_th_menu_005fcategory_005f1);
    try {
      _jspx_th_menu_005fcategory_005f1.setJspContext(_jspx_page_context);
      _jspx_th_menu_005fcategory_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/menu.jspx(11,55) name = z type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fcategory_005f1.setZ("user-managed");
      // /WEB-INF/views/menu.jspx(11,55) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fcategory_005f1.setId("c_LB2437");
      _jspx_th_menu_005fcategory_005f1.setJspBody(new Helper( 2, _jspx_page_context, _jspx_th_menu_005fcategory_005f1, null));
      _jspx_th_menu_005fcategory_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_menu_005fcategory_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_menu_005fitem_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  menu:item
    org.apache.jsp.tag.web.menu.item_tagx _jspx_th_menu_005fitem_005f1 = new org.apache.jsp.tag.web.menu.item_tagx();
    _jsp_getInstanceManager().newInstance(_jspx_th_menu_005fitem_005f1);
    try {
      _jspx_th_menu_005fitem_005f1.setJspContext(_jspx_page_context);
      _jspx_th_menu_005fitem_005f1.setParent(_jspx_parent);
      // /WEB-INF/views/menu.jspx(12,95) name = z type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f1.setZ("user-managed");
      // /WEB-INF/views/menu.jspx(12,95) name = url type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f1.setUrl("/emailsendlogs/listEmailSendLog");
      // /WEB-INF/views/menu.jspx(12,95) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_menu_005fitem_005f1.setId("i_LB2438");
      _jspx_th_menu_005fitem_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_menu_005fitem_005f1);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_menu_005fcategory_005f0(_jspx_parent, _jspx_page_context))
        return true;
      if (_jspx_meth_menu_005fcategory_005f1(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_menu_005fitem_005f0(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      if (_jspx_meth_menu_005fitem_005f1(_jspx_parent, _jspx_page_context))
        return true;
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
